version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /appdata/bazarr:/config
      - /srv/dev-disk-by-uuid-08d98c61-c13c-41a5-ba6a-73145186723e/data/media/movies:/movies
      - /srv/dev-disk-by-uuid-08d98c61-c13c-41a5-ba6a-73145186723e/data/media/movies-kids:/movies-kids      
      - /srv/dev-disk-by-uuid-08d98c61-c13c-41a5-ba6a-73145186723e/data/media/tv:/tv  
