version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /appdata/bazarr:/config
      - /data:/data # moet gelijk zijn aan hoe het bij sonarr en radarr staat genoemd
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
